# Generated by Django 5.0.7 on 2024-11-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.PositiveBigIntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('categorias', models.ManyToManyField(related_name='productos', to='perritos.categoria')),
            ],
        ),
    ]
