# Generated by Django 5.0.6 on 2024-11-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_veterinarias/'),
        ),
    ]
