# Generated by Django 5.0.6 on 2024-11-30 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0002_categoria_producto'),
        ('perritos', '0002_veterinaria_imagen'),
    ]

    operations = [
    ]
