# Generated by Django 5.1.3 on 2024-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perritos', '0003_merge_0002_categoria_producto_0002_veterinaria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perrito',
            name='sexo',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Macho', max_length=6),
        ),
    ]
